### ISSUE TITLE
`method_missing': undefined method `whitelist_attributes=' for ActiveRecord::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by alindeman** [rails/protected_attributes#5]
1) Create a new app with Rails 3.2.8
2) Upgrade it to Rails 4:

``` ruby
# Gemfile
gem 'rails', github: 'rails/rails'
gem 'activerecord-deprecated_finders', github: 'rails/activerecord-deprecated_finders'
gem 'journey', github: 'rails/journey'
```

3) Add `protected_attributes`:

``` ruby
# Gemfile
gem 'protected_attributes', github: 'rails/protected_attributes'
```

4) Attempt to run `bundle exec rails console`:

```
/Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `whitelist_attributes=' for ActiveRecord::Base:Class (NoMethodError)
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activerecord/lib/active_record/railtie.rb:96:in `block (3 levels) in <class:Railtie>'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activerecord/lib/active_record/railtie.rb:95:in `each'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activerecord/lib/active_record/railtie.rb:95:in `block (2 levels) in <class:Railtie>'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activesupport/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activesupport/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activesupport/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activesupport/lib/active_support/lazy_load_hooks.rb:27:in `each'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activesupport/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/activerecord/lib/active_record/railtie.rb:94:in `block in <class:Railtie>'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/railties/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/railties/lib/rails/initializable.rb:30:in `run'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/railties/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /Users/alindeman/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
        from /Users/alindeman/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
        from /Users/alindeman/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
        from /Users/alindeman/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
        from /Users/alindeman/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/tsort.rb:180:in `each'
        from /Users/alindeman/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
        from /Users/alindeman/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/railties/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/railties/lib/rails/application.rb:185:in `initialize!'
        from /Users/alindeman/.rvm/gems/ruby-1.9.3-p286/bundler/gems/rails-b1fe78e0cb81/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /Users/alindeman/workspace/upgradedrails3app/config/environment.rb:5:in `<top (required)>'
```

**Comment by brauliobo** [comment]
having this problem now: https://github.com/rails/rails/issues/13740
