### ISSUE TITLE
StackTrace when use protected_attributes in gem

### ISSUE THREAD

**Issue by skarm61** [rails/protected_attributes#66]
I want to use protected_attributes gem in gem with models(and migrations). It works correctly in this gem - all migrations and specs pass, but when i try to rebuild database in main application, which uses gem with models, i got such error(I try to do it in a few different applications and gems with the same result).

```
StandardError: An error has occurred, this and all later migrations canceled:

PG::NotNullViolation: ERROR:  null value in column "version" violates not-null constraint
DETAIL:  Failing row contains (null).
: INSERT INTO "models"."schema_migrations" DEFAULT VALUES/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `async_exec'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `block in exec_no_cache'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `exec_no_cache'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:177:in `exec_insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/relation.rb:64:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:503:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:306:in `block in _create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:306:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/timestamp.rb:57:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:483:in `create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:302:in `create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:125:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/validations.rb:57:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `block in save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/protected_attributes-1.0.9/lib/active_record/mass_assignment_security/validations.rb:17:in `create!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/schema_migrator-0.2.0/lib/schema_migrator/rake_task.rb:183:in `record_version_state_after_migrating'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:999:in `block in execute_migration_in_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/pg_saurus-2.2.1/lib/pg_saurus/create_index_concurrently.rb:207:in `ddl_transaction_with_postponed_queries'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:959:in `block in migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `each'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:814:in `up'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:792:in `migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/schema_migrator-0.2.0/lib/schema_migrator/rake_task.rb:29:in `block (2 levels) in define_rake_tasks!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.1.2@my_application/bin/ruby_executable_hooks:15:in `<main>'
ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "version" violates not-null constraint
DETAIL:  Failing row contains (null).
: INSERT INTO "models"."schema_migrations" DEFAULT VALUES
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `async_exec'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `block in exec_no_cache'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `exec_no_cache'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:177:in `exec_insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/relation.rb:64:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:503:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:306:in `block in _create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:306:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/timestamp.rb:57:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:483:in `create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:302:in `create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:125:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/validations.rb:57:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `block in save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/protected_attributes-1.0.9/lib/active_record/mass_assignment_security/validations.rb:17:in `create!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/schema_migrator-0.2.0/lib/schema_migrator/rake_task.rb:183:in `record_version_state_after_migrating'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:999:in `block in execute_migration_in_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/pg_saurus-2.2.1/lib/pg_saurus/create_index_concurrently.rb:207:in `ddl_transaction_with_postponed_queries'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:959:in `block in migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `each'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:814:in `up'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:792:in `migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/schema_migrator-0.2.0/lib/schema_migrator/rake_task.rb:29:in `block (2 levels) in define_rake_tasks!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.1.2@my_application/bin/ruby_executable_hooks:15:in `<main>'
PG::NotNullViolation: ERROR:  null value in column "version" violates not-null constraint
DETAIL:  Failing row contains (null).
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `async_exec'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `block in exec_no_cache'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql_adapter.rb:822:in `exec_no_cache'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/postgresql/database_statements.rb:177:in `exec_insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/relation.rb:64:in `insert'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:503:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:306:in `block in _create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:306:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/timestamp.rb:57:in `_create_record'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:483:in `create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:82:in `run_callbacks'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:302:in `create_or_update'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/persistence.rb:125:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/validations.rb:57:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `block in save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:273:in `save!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/protected_attributes-1.0.9/lib/active_record/mass_assignment_security/validations.rb:17:in `create!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/schema_migrator-0.2.0/lib/schema_migrator/rake_task.rb:183:in `record_version_state_after_migrating'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:999:in `block in execute_migration_in_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `ddl_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/pg_saurus-2.2.1/lib/pg_saurus/create_index_concurrently.rb:207:in `ddl_transaction_with_postponed_queries'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:959:in `block in migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `each'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:814:in `up'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/activerecord-4.1.9/lib/active_record/migration.rb:792:in `migrate'
/home/user/.rvm/gems/ruby-2.1.2@my_application/gems/schema_migrator-0.2.0/lib/schema_migrator/rake_task.rb:29:in `block (2 levels) in define_rake_tasks!'
/home/user/.rvm/gems/ruby-2.1.2@my_application/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.1.2@my_application/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:rebuild => db:migrate => app:db:migrate => app:models_core:db:migrate
(See full trace by running task with --trace).
```

**Comment by skarm61** [comment]
It was conflict with another gem.
